# Generated by Django 5.1.5 on 2025-01-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0002_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='sub_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
