# Generated by Django 5.1.5 on 2025-01-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0003_stamp_sub_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
