# Generated by Django 5.1.5 on 2025-01-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0004_stamp_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
