# Generated by Django 5.1.5 on 2025-01-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0005_stamp_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='size',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
