# Generated by Django 5.1.5 on 2025-01-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0007_alter_stamp_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stamp',
            name='y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
