# Generated by Django 5.1.5 on 2025-02-03 14:40

from django.db import migrations
import uuid

def populate_verification_token(apps, schema_editor):
    CustomUser = apps.get_model("stamps", "CustomUser")
    for user in CustomUser.objects.filter(verification_token__isnull=True):
        user.verification_token = uuid.uuid4()
        user.save(update_fields=["verification_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0009_customuser_is_verified_customuser_otp_code_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_verification_token, reverse_code=migrations.RunPython.noop),
    ]
