# Generated by Django 5.1.5 on 2025-02-03 15:22

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0010_auto_20250203_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 4, 15, 22, 58, 448561, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
