# Generated by Django 5.1.5 on 2025-02-04 05:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stamps', '0011_alter_customuser_verification_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 5, 9, 46, 884625, tzinfo=datetime.timezone.utc)),
        ),
    ]
